# Generated by Django 4.1.7 on 2023-03-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('0', 'Int'), ('1', 'Float'), ('2', 'Str')], max_length=1),
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eav_products.productattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eav_products.category')),
            ],
        ),
    ]
