# Generated by Django 4.1.7 on 2023-03-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav_products', '0002_category_alter_productattribute_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteav',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eav_products.category'),
            preserve_default=False,
        ),
    ]
